CREATE DATABASE IF NOT EXISTS meteoNews CHARSET utf8mb4;
USE meteoNews;

CREATE TABLE IF NOT EXISTS city_datas(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) UNIQUE NOT NULL,
    latitue VARCHAR(50) UNIQUE NOT NULL,
    longitude VARCHAR(50) UNIQUE NOT NULL,
    elevation VARCHAR(50) NOT NULL)ENGINE=innoDB;
CREATE TABLE IF NOT EXISTS today(
    id INT PRIMARY KEY AUTO_INCREMENT,
    currentDate DATE UNIQUE NOT NULL,
    TC DECIMAL UNIQUE NOT NULL,
    TCmax DECIMAL UNIQUE NOT NULL,
    TCmin DECIMAL NOT NULL,
    sunrise VARCHAR(50) NOT NULL,
    sunset VARCHAR(50) NOT NULL,
    pressure DECIMAL NOT NULL,
    humidity VARCHAR(50) NOT NULL)ENGINE=innoDB;